apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=flaskappstoragecloud;AccountKey=...;BlobEndpoint=https://..."
